#!/usr/bin/env bash
# Bumshi installer.
#
# Recommended (process substitution keeps prompts interactive):
#   bash <(curl -Ls https://raw.githubusercontent.com/bumshi/bumshi/main/install.sh)
#   bash <(wget -qO- https://raw.githubusercontent.com/bumshi/bumshi/main/install.sh)
#
# Non-interactive (CI/automation): set BUMSHI_* variables and pipe, e.g.
#   BUMSHI_DOMAIN=proxy.example.com BUMSHI_ADMIN_PASSWORD=... curl -Ls URL | bash
#
# It installs the bumshid binary (checksum-verified), a hardened systemd unit,
# the management command, an env file, and optionally Caddy for automatic HTTPS.
# It is idempotent: re-running updates the binary and keeps existing config
# unless you choose to reconfigure.
set -euo pipefail

REPO="${BUMSHI_REPO:-bumshi/bumshi}"
REF="${BUMSHI_REF:-main}"          # branch/tag for helper files (unit, mgmt script)
VERSION="${BUMSHI_VERSION:-latest}" # release tag for the binary, or "latest"

BIN_DIR="/usr/local/bin"
BINARY="${BIN_DIR}/bumshid"
MGMT="${BIN_DIR}/bumshi"
ETC_DIR="/etc/bumshi"
ENV_FILE="${ETC_DIR}/bumshi.env"
UNIT="/etc/systemd/system/bumshi.service"
SERVICE_USER="bumshi"
CADDYFILE="/etc/caddy/Caddyfile"

c_reset="\033[0m"; c_teal="\033[36m"; c_red="\033[31m"; c_yellow="\033[33m"; c_dim="\033[2m"
info() { echo -e "${c_teal}==>${c_reset} $*"; }
warn() { echo -e "${c_yellow}warning:${c_reset} $*" >&2; }
err()  { echo -e "${c_red}error:${c_reset} $*" >&2; }
die()  { err "$*"; exit 1; }

have() { command -v "$1" >/dev/null 2>&1; }
interactive() { [ -t 0 ]; }
require_root() { [ "$(id -u)" -eq 0 ] || die "please run as root (try: sudo bash ...)"; }

raw_url() { echo "https://raw.githubusercontent.com/${REPO}/${REF}/$1"; }
rel_url() { echo "https://github.com/${REPO}/releases/download/$1/$2"; }

download() { # download URL OUT
  if have curl; then curl -fsSL "$1" -o "$2"
  elif have wget; then wget -qO "$2" "$1"
  else die "need curl or wget"; fi
}
fetch() { # fetch URL -> stdout
  if have curl; then curl -fsSL "$1"
  elif have wget; then wget -qO- "$1"
  else die "need curl or wget"; fi
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64) echo amd64 ;;
    aarch64|arm64) echo arm64 ;;
    *) die "unsupported architecture: $(uname -m)" ;;
  esac
}

gen_password() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 16; }

prompt() { # prompt VAR "question" "default"
  local __var="$1" q="$2" def="${3:-}" ans
  if ! interactive; then printf -v "$__var" '%s' "$def"; return; fi
  if [ -n "$def" ]; then read -rp "$q [$def]: " ans || true; else read -rp "$q: " ans || true; fi
  printf -v "$__var" '%s' "${ans:-$def}"
}

confirm() { # confirm "question" default(y|n)
  local q="$1" def="${2:-n}" ans hint
  if ! interactive; then [ "$def" = "y" ]; return; fi
  [ "$def" = "y" ] && hint="Y/n" || hint="y/N"
  read -rp "$q [$hint]: " ans || true
  ans="${ans:-$def}"
  [[ "$ans" =~ ^[Yy]$ ]]
}

# ---- steps ----

resolve_latest() {
  fetch "https://api.github.com/repos/${REPO}/releases/latest" \
    | grep -m1 '"tag_name"' \
    | sed -E 's/.*"tag_name":[[:space:]]*"([^"]+)".*/\1/'
}

install_binary() { # install_binary TAG ARCH
  local tag="$1" arch="$2" asset="bumshid_linux_$2" tmp
  tmp="$(mktemp -d)"
  info "downloading ${asset} (${tag})"
  download "$(rel_url "$tag" "$asset")" "${tmp}/${asset}"
  download "$(rel_url "$tag" checksums.txt)" "${tmp}/checksums.txt"
  info "verifying checksum"
  ( cd "$tmp" && grep " ${asset}\$" checksums.txt | sha256sum -c - >/dev/null ) \
    || { rm -rf "$tmp"; die "checksum verification failed"; }
  install -m 0755 "${tmp}/${asset}" "$BINARY"
  rm -rf "$tmp"
  info "installed ${BINARY}"
}

ensure_user() {
  if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER" 2>/dev/null \
      || useradd --system --no-create-home --shell /bin/false "$SERVICE_USER"
    info "created system user ${SERVICE_USER}"
  fi
}

install_unit() {
  info "installing systemd unit"
  download "$(raw_url deploy/systemd/bumshi.service)" "$UNIT" \
    || die "could not download systemd unit"
  systemctl daemon-reload
}

install_mgmt() {
  if download "$(raw_url bumshi.sh)" "$MGMT" 2>/dev/null; then
    chmod 0755 "$MGMT"
    info "installed management command: bumshi"
  else
    warn "could not fetch management script (bumshi.sh)"
  fi
}

write_env() {
  local hash=""
  if [ -n "$admin_pass" ]; then
    hash="$(printf '%s\n' "$admin_pass" | "$BINARY" hash-password 2>/dev/null)" \
      || die "failed to hash admin password"
  fi
  mkdir -p "$ETC_DIR"
  ( umask 077; cat > "$ENV_FILE" <<EOF
# Generated by install.sh — edit and then: bumshi restart
BUMSHI_ENV=production
BUMSHI_LISTEN_ADDR=127.0.0.1:8080
BUMSHI_METRICS_ADDR=127.0.0.1:9090
BUMSHI_ACCESS_LOG=false

BUMSHI_PROXY_ENABLED=${enable_proxy}

BUMSHI_ADMIN_ENABLED=true
BUMSHI_ADMIN_PATH=${admin_path}
BUMSHI_ADMIN_USERNAME=${admin_user}
BUMSHI_ADMIN_PASSWORD_HASH=${hash}
BUMSHI_PUBLIC_URL=${public_url}
EOF
  )
  chown -R "$SERVICE_USER:$SERVICE_USER" "$ETC_DIR"
  chmod 640 "$ENV_FILE"
  info "wrote ${ENV_FILE}"
}

install_caddy_pkg() {
  have apt-get || return 1
  info "installing Caddy"
  apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl gnupg >/dev/null 2>&1 || true
  curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/gpg.key \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt \
    | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
  apt-get update -y >/dev/null && apt-get install -y caddy >/dev/null
}

setup_caddy() {
  if [ -z "$domain" ]; then
    warn "no domain set — skipping TLS/Caddy. Point your own reverse proxy at 127.0.0.1:8080."
    return
  fi
  if ! have caddy; then
    if confirm "Caddy (automatic HTTPS) is not installed. Install it now?" y; then
      install_caddy_pkg || { warn "Caddy install failed; set up TLS manually"; return; }
    else
      warn "skipping Caddy; set up your own TLS to 127.0.0.1:8080"; return
    fi
  fi
  mkdir -p "$(dirname "$CADDYFILE")"
  cat > "$CADDYFILE" <<EOF
{
	email ${email}
}

${domain} {
	encode gzip
	header -Server
	reverse_proxy 127.0.0.1:8080
}
EOF
  systemctl reload caddy 2>/dev/null || systemctl restart caddy 2>/dev/null \
    || warn "could not reload Caddy; check: systemctl status caddy"
  info "configured Caddy for ${domain}"
}

summary() {
  echo
  info "Bumshi installed and running."
  echo "  Status:  systemctl status bumshi"
  echo "  Manage:  bumshi menu"
  if [ -n "$domain" ]; then
    echo "  Panel:   https://${domain}${admin_path}"
  else
    echo "  Panel:   http://<server-ip>:8080${admin_path}  (add TLS for production)"
  fi
  echo "  Login:   ${admin_user}"
  if [ "${gen_note:-0}" = "1" ]; then
    echo -e "  ${c_yellow}Password (save it now — shown once): ${admin_pass}${c_reset}"
  fi
  if [ "${behind_cf:-n}" = "y" ]; then
    echo -e "  ${c_dim}Cloudflare: proxy the DNS record for ${domain} and set SSL/TLS mode to Full (strict).${c_reset}"
  fi
}

main() {
  require_root
  info "Bumshi installer"

  local arch tag
  arch="$(detect_arch)"
  info "target: linux/${arch}"

  tag="$VERSION"
  if [ "$tag" = "latest" ]; then
    tag="$(resolve_latest || true)"
    [ -n "$tag" ] || die "could not resolve the latest release; set BUMSHI_VERSION=vX.Y.Z"
  fi

  # Config, seeded from environment for non-interactive installs.
  domain="${BUMSHI_DOMAIN:-}"
  email="${BUMSHI_EMAIL:-}"
  admin_user="${BUMSHI_ADMIN_USERNAME:-admin}"
  admin_pass="${BUMSHI_ADMIN_PASSWORD:-}"
  admin_path="${BUMSHI_ADMIN_PATH:-/admin/}"
  public_url="${BUMSHI_PUBLIC_URL:-}"
  enable_proxy="${BUMSHI_ENABLE_PROXY:-true}"
  behind_cf="n"
  gen_note=0

  local reconfigure="y"
  if [ -f "$ENV_FILE" ] && interactive; then
    confirm "Existing config found at ${ENV_FILE}. Reconfigure it?" n || reconfigure="n"
  fi

  # Always update the binary, user, unit, and management command.
  install_binary "$tag" "$arch"
  ensure_user
  install_unit
  install_mgmt

  if [ "$reconfigure" = "y" ]; then
    prompt domain "Domain (e.g. proxy.example.com), blank to skip TLS" "$domain"
    [ -z "$email" ] && email="admin@${domain:-example.com}"
    prompt email "Email for Let's Encrypt" "$email"
    if interactive; then
      confirm "Enable the web proxy engine now?" y && enable_proxy="true" || enable_proxy="false"
    fi
    prompt admin_user "Admin username" "$admin_user"
    if [ -z "$admin_pass" ] && interactive; then
      prompt admin_pass "Admin password (blank to auto-generate)" ""
    fi
    if [ -z "$admin_pass" ]; then admin_pass="$(gen_password)"; gen_note=1; fi
    prompt admin_path "Admin panel path" "$admin_path"
    [[ "$admin_path" == /* ]] || admin_path="/$admin_path"
    [[ "$admin_path" == */ ]] || admin_path="$admin_path/"
    if [ -n "$domain" ]; then
      public_url="https://${domain}"
    else
      prompt public_url "Public URL for connection links" "$public_url"
    fi
    interactive && { confirm "Will you put this behind Cloudflare?" n && behind_cf="y" || behind_cf="n"; }

    write_env
    setup_caddy
  else
    info "keeping existing configuration"
  fi

  systemctl enable --now bumshi
  summary
}

main "$@"
